#pragma once
#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QHash>
#include <QList>
#include <QMainWindow>
#include <QPoint>
#include <QString>
#include <QStringList>
#include <QUrl>

// Forward declarations keep the header light and avoid exposing implementation
// details from the Qt classes used by the window.
class BrowserPane;
class BrowserLineEdit;
class DirectorySizeSortProxyModel;
// Window-level pinned-directory panel (not per-tab).
class PinnedSidebar;
class QAbstractItemView;
class QCloseEvent;
class QEvent;
class QSplitter;
class QTimer;
class QWidget;
class QTreeView;
class QLabel;
class QPushButton;
class QModelIndex;
class QPoint;

QT_BEGIN_NAMESPACE
namespace Ui {
// Generated by uic from mainwindow.ui.
class MainWindow;
}
QT_END_NAMESPACE

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    // Creates the main window and its initial browser tab.
    explicit MainWindow(QWidget *parent = nullptr);
    // Cleans up the generated UI object owned by this window.
    ~MainWindow();

protected:
    // Flush the last sidebar width before the window actually closes.
    void closeEvent(QCloseEvent *event) override;

    // Keep the bottom search field aligned when the sidebar moves or resizes.
    bool eventFilter(QObject *watched, QEvent *event) override;

private:
    // One real tab page contains exactly one BrowserPane. The owning tab
    // widget identifies whether that page belongs to the left or right group.
    struct TabState {
        QTabWidget *tabWidget = nullptr;
        BrowserPane *activePane = nullptr;
    };

    // The widgets generated from mainwindow.ui.
    Ui::MainWindow *ui;

    // Shared proxy that provides filesystem data, lazy sizes, and sorting.
    DirectorySizeSortProxyModel *fileModel;

    // Tracks the pane and owning tab group for every real browser tab page.
    QHash<QWidget *, TabState> tabStates;

    // Horizontal workspace splitter containing one or two independent tab
    // groups. Each QTabWidget is constrained to its own splitter allocation.
    QSplitter *browserPaneSplitter = nullptr;

    // Visual left-to-right list of independent tab groups. activeTabWidget is
    // updated by tab clicks and pane interaction and receives Ctrl+T tabs.
    QList<QTabWidget *> paneTabWidgets;
    QTabWidget *activeTabWidget = nullptr;

    // Every group has its own trailing plus placeholder. Mapping by tab widget
    // prevents one group's plus tab from being mistaken for another's.
    QHash<QTabWidget *, QWidget *> newTabPlaceholders;

    // Window-level sidebar of pinned directories, shared by every tab.
    PinnedSidebar *pinnedSidebar = nullptr;
    // Horizontal splitter: sidebar | tab widget. Not inside each tab page.
    QSplitter *sidebarSplitter = nullptr;
    // Last expanded sidebar width, restored after collapse.
    int expandedSidebarWidth = 180;
    // Coalesces QSettings writes so splitterMoved does not hit disk per pixel.
    QTimer *sidebarLayoutSaveTimer = nullptr;

    // The bottom search field filters the active pane only. The adjacent view
    // buttons switch that pane's presentation between details and icon grids.
    QWidget *bottomControlsWidget = nullptr;
    BrowserLineEdit *fileSearchLineEdit = nullptr;
    QPushButton *detailsViewButton = nullptr;
    QPushButton *smallIconsViewButton = nullptr;
    QPushButton *bigIconsViewButton = nullptr;
    QLabel *fileCountLabel = nullptr;

    // Insert the sidebar, restore width/collapsed, and connect navigation.
    void setupSidebar();
    // Apply strip width or expandedSidebarWidth to the splitter.
    void applySidebarSplitterSizes();
    // Match the search field's horizontal edges to the live sidebar frame.
    void alignBottomControlsToSidebar();
    // Restart the short save timer; the actual write happens after dragging.
    void scheduleSidebarLayoutSave();
    // Write sidebar/width and sidebar/collapsed to QSettings.
    void saveSidebarLayout();

    // Add left-aligned Search and view controls plus a right-aligned regular-
    // file count to the status bar, synchronized with the active pane.
    void setupViewModeControls();
    void updateViewModeControls();

    // Resolve the pane in the current tab of the most recently active group.
    BrowserPane *activeBrowserPane() const;

    // Build a new tab in the active tab group.
    void createTab(const QString &path);

    // Build a new tab in one explicit group. Plus buttons and session restore
    // use this overload so they never fall back to the left group.
    QWidget *createTabInGroup(
        QTabWidget *tabWidget,
        const QString &path
    );

    // Configure one independent tab group and its trailing plus control.
    void setupPaneTabWidget(QTabWidget *tabWidget);

    // Create and register a second tab group inside browserPaneSplitter.
    QTabWidget *createPaneTabWidget();

    // Create a pane, attach the shared model, and wire its signals.
    BrowserPane *createBrowserPane(QWidget *page);

    // Connect activation, split/close, drops, and the file-view actions.
    void setupPaneConnections(QWidget *page, BrowserPane *pane);

    // Split controls are available with one group; pane-close controls are
    // available with two. Recompute every pane after structural changes.
    void updatePaneChrome();

    // Add a second independent tab group beside the active one, starting with
    // a tab at the requesting pane's path. No-op when two groups already exist.
    void splitPane(QWidget *page);

    // Close the requesting tab group. The final remaining group cannot close.
    void closePane(QWidget *page, BrowserPane *pane);

    // Remember which pane should receive pin clicks and file actions.
    void setActivePane(QWidget *page, BrowserPane *pane);

    // Make the current tab in the leftmost group the active keyboard target.
    // Called after a two-pane workspace is created or restored.
    void focusLeftPane();

    // Visible file view belonging to the tab's active pane, or null if gone.
    QAbstractItemView *fileViewForPage(QWidget *page) const;

    // Copy dropped or pasted URLs into dest using copyRecursively.
    void copyUrlsIntoDirectory(
        const QList<QUrl> &urls,
        const QString &destinationDirectory
    );

    // Persist every tab's pane paths, histories, and splitter sizes.
    void saveSession() const;

    // Recreate tabs from QSettings. Returns false when nothing was stored.
    bool restoreSession();

    // --------------------------------------------
    // Navigation
    // --------------------------------------------

    // Moves the active pane to a directory and optionally records history.
    void navigateTo(QWidget *page, const QString &path, bool addToHistory = true);

    void openDirectory(QWidget *page, const QModelIndex &index);



    // -----------------------------------------------------
    // State change
    // -----------------------------------------------------

    // Updates the visible tab text based on the left pane's directory name.
    void updateTabTitle(QWidget *page, const QString &path);

    // ------------------------------------------------------
    // Actions
    // -------------------------------------------------------

    // Show the right-click menu for the file view.
    void showFileContextMenu(
        QWidget *page,
        QAbstractItemView *fileView,
        const QPoint &position
    );

    // Open a directory in TurboFile or open a file
    // using the desktop's default application.
    // Open one specific item.
    // Used primarily by double-clicking.
    void openItem(
        QWidget *page,
        const QModelIndex &index
    );

    // Open every currently selected item.
    void openSelectedItems(
        QWidget *page
    );

    // Copy all selected filesystem items
    // to the desktop clipboard.
    void copySelectedItemsToClipboard(
        QWidget *page
    );

    // Rename the selected item.
    // Only works when exactly one item is selected.
    void renameSelectedItem(
        QWidget *page
    );

    // Move all selected items to Trash.
    void deleteSelectedItems(
        QWidget *page
    );

    // Copy all filesystem URLs from the clipboard into the current directory.
    void pasteClipboardItems(
        QWidget *page
    );

    // Create an empty file inside the directory displayed by this tab.
    void createNewFile(QWidget *page);

    // Create an empty folder inside the directory displayed by this tab.
    void createNewFolder(QWidget *page);

    // Launch the user's installed terminal with this tab's directory as its
    // working directory.
    void openTerminalHere(QWidget *page);

    // Open a highlighted Bash editor and execute its script in this tab's
    // displayed directory.
    void runShellScriptHere(QWidget *page);

    // Copy every selected item beside its source using a collision-safe name.
    void duplicateSelectedItems(QWidget *page);

    // Resolve the filesystem directory represented by a tab's root index.
    QString currentDirectoryPath(QWidget *page) const;

    // Return the filesystem paths represented
    // by the selected rows in either file presentation.
    QStringList selectedFilePaths(
        QAbstractItemView *fileView
    ) const;

    // Recursively copy either a file or directory.
    bool copyRecursively(
        const QString &sourcePath,
        const QString &destinationPath
    );

    // Generate a destination name that doesn't overwrite
    // something that already exists.
    QString makeUniqueCopyPath(
        const QString &sourcePath,
        const QString &destinationDirectory
    ); 


    // Column sort
    void configureFileTreeView(
        QTreeView *fileTreeView
    );
};

#endif // MAINWINDOW_H


