#pragma once
#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QString>
#include <QStringList>
#include <QHash>
#include <QMainWindow>
#include <QPoint>

// Forward declarations keep the header light and avoid exposing implementation
// details from the Qt classes used by the window.
class QFileSystemModel;
class QWidget;
class QTreeView;
class QLineEdit;
class QPushButton;
class QModelIndex;
class QPoint;

QT_BEGIN_NAMESPACE
namespace Ui {
// Generated by uic from mainwindow.ui.
class MainWindow;
}
QT_END_NAMESPACE

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    // Creates the main window and its initial browser tab.
    explicit MainWindow(QWidget *parent = nullptr);
    // Cleans up the generated UI object owned by this window.
    ~MainWindow();

private:
    // Stores the per-tab widgets and history needed for navigation buttons.
    struct TabState {
        QTreeView *fileTreeView = nullptr;
        QLineEdit *pathLineEdit = nullptr;
        QPushButton *backButton = nullptr;
        QPushButton *forwardButton = nullptr;
        QStringList history;
        int historyIndex = -1;
    };

    // The widgets generated from mainwindow.ui.
    Ui::MainWindow *ui;

    // Shared model that provides the filesystem data shown in each tab.
    QFileSystemModel *fileModel;

    // Tracks the state for every browser tab, keyed by the tab page widget.
    QHash<QWidget *, TabState> tabStates;

    // Builds a new tab rooted at the supplied directory.
    void createTab(const QString &path);

    // Connects the signals for one browser tab's widgets.
    void setupTabConnections(
        QWidget *page,
        QPushButton *backButton,
        QPushButton *forwardButton,
        QPushButton *upButton,
        QTreeView *fileTreeView
    );

    // --------------------------------------------
    // Navigation
    // --------------------------------------------


    // Navigate to the path manually entered in the path bar.
    void navigateFromPathBar(QWidget *page);

    // Move one level upward in the current filesystem view.
    void goUp(QWidget *page);

    // Move backward in the current tab's browsing history.
    void goBack(QWidget *page);

    // Move forward in the current tab's browsing history.
    void goForward(QWidget *page);

    // Moves the tab view to a directory and optionally records it in history.
    void navigateTo(QWidget *page, const QString &path, bool addToHistory = true);

    void openDirectory(QWidget *page, const QModelIndex &index);



    // -----------------------------------------------------
    // State change
    // -----------------------------------------------------

    // Updates the visible tab text based on the current directory name.
    void updateTabTitle(QWidget *page, const QString &path);

    // Enables or disables the Back and Forward buttons based on history state.
    void updateNavigationButtons(QWidget *page);

    // ------------------------------------------------------
    // Actions
    // -------------------------------------------------------

    // Show the right-click menu for the file view.
    void showFileContextMenu(
        QWidget *page,
        const QPoint &position
    );

    // Open a directory in TurboFile or open a file
    // using the desktop's default application.
    // Open one specific item.
    // Used primarily by double-clicking.
    void openItem(
        QWidget *page,
        const QModelIndex &index
    );

    // Open every currently selected item.
    void openSelectedItems(
        QWidget *page
    );

    // Copy all selected filesystem items
    // to the desktop clipboard.
    void copySelectedItemsToClipboard(
        QWidget *page
    );

    // Rename the selected item.
    // Only works when exactly one item is selected.
    void renameSelectedItem(
        QWidget *page
    );

    // Move all selected items to Trash.
    void deleteSelectedItems(
        QWidget *page
    );

    // Copy all filesystem URLs from the clipboard into the current directory.
    void pasteClipboardItems(
        QWidget *page
    );

    // Return the filesystem paths represented
    // by the selected rows in a tree.
    QStringList selectedFilePaths(
        QTreeView *fileTreeView
    ) const;

    // Recursively copy either a file or directory.
    bool copyRecursively(
        const QString &sourcePath,
        const QString &destinationPath
    );

    // Generate a destination name that doesn't overwrite
    // something that already exists.
    QString makeUniqueCopyPath(
        const QString &sourcePath,
        const QString &destinationDirectory
    ); 


    // Column sort
    void configureFileTreeView(
        QTreeView *fileTreeView
    );
};

#endif // MAINWINDOW_H


